---
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
# load packages and set seed
packages=c("psych","dplyr","lavaan","parameters","papaja","irr","osfr","openxlsx","mltools","irrCAC") 
set.seed(626461321)

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages], repos = "https://cran.r-project.org/")
}
# Packages loading
invisible(lapply(packages, library, character.only = TRUE))


library("papaja")
r_refs("r-references.bib")
```

```{r data loading, include=FALSE}
data <- openxlsx::read.xlsx( paste0(getwd(),"/Data/abs_scr_eval_res_JH_PM.xlsx"))

# old data to check
data.old.ratng <- openxlsx::read.xlsx( paste0(getwd(),"/Data/abs_scr_eval_res_JH_PM_old_old.xlsx"))
```

```{r Inter-rater reliability and percent agreement}
# set seed in order to assure computaional reproducitiblity
set.seed(874354)

# percent ageement
agree(data, tolerance=0) 

# cohens kappa
kappa2(ratings = data) # cohens kappa yields contraceptive values, thus other method i.e. Matthews correlation coefficient was used for the analysis of agreement. 

# Matthews correlation coefficient (dodat zdůvodnění proč zrovna toto)
mltools::mcc(data$PM, data$JH) %>% round(digits = 2) 

# Gwet´s AC1
gwen=irrCAC::gwet.ac1.raw(ratings = data)
```



\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
